query getUser{
  user{
    id
    username
    avatar
    email
    accessToken
    guilds{
      id
      name
      icon
      owner
      permissions
      features
      permissions_new
    }
  }
}
